version: "3.7"
services:
  peanut_app:
    build: .
    restart: always
    container_name: peanut_app
    volumes:
      - ./app
    environment:
      - PEANUT_CUSTOM_VAR=set_by_docker_env_var
    ports:
      - "5000:5000"
